automatic_submission: false
award: UM1HG009443
description: Mouse ENCODE cortex
disk_mb: 51200
encode_portal_host: test.encodedcc.org
experiment_accession: ENCODE_Cortex
# for human: (urls are included because the genome_accessions are currently not released)
# genome_accession: encode:starsolo-GRCh38-V29-male-index
# genome_index_url: https://woldlab.caltech.edu/~diane/genome/GRCh38-V29-male-2.7.8a.tar.gz
genome_accession: encode:starsolo-mm10-M21-male-index
genome_index_url: https://woldlab.caltech.edu/~diane/genome/mm10-M21-male-2.7.9a/mm10-M21-male-2.7.9a-star.tar.gz
include_intron: true
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library_accession: C_18m_F_2
mem_mb: 65536
# will expect a file named get {read1}_R1.fastq.gz
read1:
- C_18m_F_2
# will expect a file named {read2}_R2.fastq.gz
read2:
- C_18m_F_2
# should be set automatically
#star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
